
$(document).ready(function(){
    dropGen("weapons",".weapon");
    dropGen("armor",".armor");
    dropGen("items",".itemSlot");
    dropGen("feats",".featSlot");
    dropGen("races","#race");
    dropGen("backgrounds","#background");
    dropGen("proficiencies",".proficiencySlot");
    dropGen("classes","#classOne");
    dropGen("classes","#classTwo");
    dropGen("alignments","#alignment");
    dropGen("personalities","#personality");
    dropGen("ideals","#ideals");
    dropGen("bonds","#bonds");
    dropGen("flaws","#flaws");
    dropGen("personalities","#customPersonality");
    displayText("weaponsSlotOne", "weapons");
    mouseMove("#weaponsSlotOne","#popup");
    displayText("weaponsSlotTwo", "weapons");
    mouseMove("#weaponsSlotTwo","#popup");
    displayText("weaponsSlotThree", "weapons");
    mouseMove("#weaponsSlotThree","#popup");
    displayText("weaponsSlotFour", "weapons");
    mouseMove("#weaponsSlotFour","#popup");
    displayText("weaponsSlotFive", "weapons");
    mouseMove("#weaponsSlotFive","#popup");
    displayText("weaponsSlotSix", "weapons");
    mouseMove("#weaponsSlotSix","#popup");
    displayText("weaponsSlotSeven", "weapons");
    mouseMove("#weaponsSlotSeven","#popup");
    displayText("weaponsSlotEight", "weapons");
    mouseMove("#weaponsSlotEight","#popup");
    abilityModifier("Strength");
    abilityModifier("Dexterity");
    abilityModifier("Constitution");
    abilityModifier("Intelligence");
    abilityModifier("Wisdom");
    abilityModifier("Charisma");
})
